### ISSUE TITLE
Does not work on 2.3

### ISSUE THREAD

**Issue by shankar2004nag** [amitshree/magento2-account-approval#10]
After registration customer is not viewable in backend
Client is able to login his account without approval of admin

**Comment by amitshree** [comment]
Which version?

Have you enabled the module at Stores => Configuration => Amitshree customer => Customer Login

**Comment by shankar2004nag** [comment]
There is issue in redirect.php and loginPost.php . When you tried to login from unapproved email id it gives 404 error

**Comment by amitshree** [comment]
Fixed. 

Please pull Plugin/Customer/Controller/Account/LoginPost.php and it should be resolved.

**Comment by shankar2004nag** [comment]
Thanx for your update.
Could we have one enhancement to redirect to the desired page instead of my account page

**Comment by amitshree** [comment]
This can be done in future versions. If you want to work on it feel free to contribute :)
For now I am closing this.
