### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by vincent2090311** [amitshree/magento2-account-approval#11]
You should change 
composer config repositories.magento2-account-approval git git@github.com:amitshree/magento2-account-approval.git
to 
composer config repositories.magento2-account-approval vcs git@github.com:amitshree/magento2-account-approval.git

to avoid installation error when install the module via composer

**Comment by amitshree** [comment]
Hi @vincent2090311 

Yesterday I have made some changes to the installation steps. Kindly check and let me know if are facing any issue.
