### ISSUE TITLE
error to install the extension

### ISSUE THREAD

**Issue by Ghadawi** [amitshree/magento2-account-approval#2]
I got error while ruining: composer require magento2-customer-account-approval:dev-master
Problem 1
    - The requested package magento2-account-approval could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for magento2-customer-account-approval dev-master -> satisfiable by magento2-customer-account-approval[dev-master].
    - magento2-customer-account-approval dev-master requires magento/module-store 100.0.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by amitshree** [comment]
Required component version check is removed. You will be able to install it now.
