### ISSUE TITLE
After registration its taking me in, The approval is not working 

### ISSUE THREAD

**Issue by fernandusfero** [amitshree/magento2-account-approval#5]
The extension works good in all scenario but when a user registers for the first time it takes me in, If i logout and get back again it ask for authentication.

**Comment by amitshree** [comment]
Which Magento version you are using?
Have you enabled extension at Stores => Configuration => Amitshree customer => Customer Login ?

**Comment by amitshree** [comment]
It has been tested and customer will not be logged in automatically on registration.
