### ISSUE TITLE
Add to customer grid

### ISSUE THREAD

**Issue by Fidelity88** [amitshree/magento2-account-approval#6]
It would be nice if we could add the attribute to the customer grid. Meaning we can go to **Admin > Customers > All Customers** and see the approval status for all customers without having to open each customer.

How can we add this?

**Comment by amitshree** [comment]
Looks like a good suggestion Maurice. It can be achieved as per the answers in the following thread:

https://magento.stackexchange.com/questions/126820/magento-2-how-to-add-a-custom-column-in-customer-grid

Please create are PR if you are developing this or I will work on it once I get some free time from my existing work.

**Comment by 900math** [comment]
> 
> 
> Looks like a good suggestion Maurice. It can be achieved as per the answers in the following thread:
> 
> https://magento.stackexchange.com/questions/126820/magento-2-how-to-add-a-custom-column-in-customer-grid
> 
> Please create are PR if you are developing this or I will work on it once I get some free time from my existing work.

Any chance you can give a hint in what the db_name is for the options? I've been trying to figure this out by the php files but can't seem to make sense of it.

**Comment by amitshree** [comment]
Can you please explain more about your question?

**Comment by 900math** [comment]
> 
> 
> Can you please explain more about your question?

Yes sure, in what SQL database field is the flag 1 = activated, 0 = not activated stored? I've been trying to find it in the magento SQL but can't seem to find the value in the customer field of the database.
