### ISSUE TITLE
Customers can't login after installation

### ISSUE THREAD

**Issue by domino4evers** [amitshree/magento2-account-approval#9]
Hi there

I have installed your extension on my  Magento ver. 2.3.1.

Run:
php -f bin/magento module:enable Amitshree_Customer
php bin/magento setup:upgrade
php bin/magento setup:di:compile
php bin/magento cache:flush
php bin/magento cache:clean

I enabled the extension in the Stores => Configuration => Amitshree customer => Customer Login. And checked the customers was set to "Approve Account = Yes"

All was OK - but i could not login, just sent me back to the loginscreen. The I disabled the extension again, but now I can't login with my customers AND the Approve Account is still visible under the  Account Information.

What can I do to uninstall the extension totally???

**Comment by amitshree** [comment]
Disable the module using `php bin/magento module:disvable Amitshree_Customer`.
Delete module from vendor folder.

Though above steps will not delete the customer attribute `approve_account` which was created earlier.
